name: Update Weather Data
on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests openmeteo_requests requests_cache retry_requests

      - name: Run the Python script
        run: python "DataScience and AI ML/Data Collection and Storage/Api_Learn/API Data Collection and Analysis/Weather.py"

