name: Update Weather Data
on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests openmeteo_requests requests_cache retry_requests

      - name: Run the Python script
        run: python "DataScience and AI ML/Data Collection and Storage/Api_Learn/API Data Collection and Analysis/Weather.py"
        working-directory: ${{ github.workspace }}

      - name: Pull latest changes from remote
        run: git pull origin main
        working-directory: ${{ github.workspace }}

      - name: Commit and Push CSV Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add 'DataScience and AI ML/Data Collection and Storage/Api_Learn/API Data Collection and Analysis/weatherdata.csv'
          git commit -m 'Update weather data'
          git push origin main
        working-directory: ${{ github.workspace }}