name: Update Weather Data
on:
  schedule:
    # Runs every 30 minutes
    - cron: '*/30 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      - name: Run the Python script
        run: python Weather.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com" # spell-checker: disable-line
          git add weather_data.csv
          git commit -m "Update weather data"
          git push
